package job

type Type uint64

const (
	TYPE_ECHO               = 0
	TYPE_CONTAINER_OPEN     = 1
	TYPE_FILE_OPEN          = 2
	TYPE_FILE_WRITE         = 3
	TYPE_FILE_READ          = 4
	TYPE_FS_ATTR_GET        = 5
	TYPE_SESSION_ACQUIRE    = 6
	TYPE_CONTAINER_CLOSE    = 7
	TYPE_FILE_CLOSE         = 8
	TYPE_FS_DIR_CREATE      = 9
	TYPE_FS_DIR_DELETE      = 10
	TYPE_FS_FILE_DELETE     = 11
	TYPE_FS_DIR_READ        = 12
	TYPE_FS_SET_ATTRS       = 13
	TYPE_RENAME             = 14
	TYPE_OBJECT_PUT         = 15
	TYPE_OBJECT_GET         = 16
	TYPE_OBJECT_DELETE      = 17
	TYPE_RECORDS_GET        = 18
	TYPE_STREAM_CREATE      = 19
	TYPE_STREAM_SEEK_SHARD  = 20
	TYPE_OBJECT_SET         = 21
	TYPE_OBJECT_ITEM_UPDATE = 22
	TYPE_OBJECT_ITEM_GET    = 23
	TYPE_OBJECT_ITEMS_GET   = 24
	TYPE_RECORDS_PUT        = 25

	TYPE_MAX = TYPE_RECORDS_PUT
)
